# -*- coding: utf-8 -*-
"""Blogger_Cleanup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4sKKWxZ8ohQWC0f-esLM8HMXfV7t5Di
"""

from bs4 import BeautifulSoup

def compare_html_and_extract_pre(original_html_file, pretty_html_file, output_file):
    """
    Extracts all <pre> elements from the original file
    and writes them to an output file.
    """
    try:
        # Read the original HTML file
        with open(original_html_file, 'r', encoding='utf-8') as f:
            orig_html_content = f.read()
        orig_soup = BeautifulSoup(orig_html_content, 'html.parser')

        # Get all <pre> elements from the original HTML
        orig_pre_elements = orig_soup.find_all('pre')

        found_pre_fragments = []

        for pre_tag in orig_pre_elements:
            # Removed the check against pretty_soup.get_text() to include all <pre> elements
            found_pre_fragments.append(str(pre_tag))

        # Write the found <pre> blocks to the output file
        if found_pre_fragments:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write("<!DOCTYPE html>\n<html>\n<head><title>Pre Fragments</title></head>\n<body>\n")
                for i, fragment in enumerate(found_pre_fragments):
                    f.write(fragment)
                    if i < len(found_pre_fragments) - 1:
                        f.write("\n<hr>\n") # Separate with a horizontal rule
                f.write("\n</body>\n</html>")
            print(f"Successfully created '{output_file}' with {len(found_pre_fragments)} pre fragments.")
        else:
            print(f"No <pre> elements found in '{original_html_file}'. '{output_file}' was not created.")

    except FileNotFoundError as e:
        print(f"Error: The input file '{original_html_file}' was not found: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Define the input and output filenames
original_file = 'post-orig.html'
pretty_file = 'post-pretty.html' # This file is no longer used for filtering, but kept for function signature consistency if needed elsewhere
output_file = 'pre-frags.html'

# Run the comparison and extraction
compare_html_and_extract_pre(original_file, pretty_file, output_file)

"""# New Section

# New Section
"""

from bs4 import BeautifulSoup

def finalize_pre_code_cleaning(input_file, output_file):
    """
    Reads an HTML file, extracts the <code> tag within each <pre> tag,
    and replaces the <pre> content with just the <code> tag, removing intermediate wrappers.
    Saves the result to a new file.
    """
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
        soup = BeautifulSoup(html_content, 'html.parser')

        all_pre_tags = soup.find_all('pre')

        for pre_tag in all_pre_tags:
            code_tag = pre_tag.find('code')
            if code_tag:
                # Remove all children of the <pre> tag
                pre_tag.clear()
                # Append only the <code> tag back to the <pre> tag
                pre_tag.append(code_tag)
            # else: If no code tag is found, the pre tag will be empty after clear(),
            # or we could choose to remove the pre_tag entirely if it's empty.
            # For this request, we keep the empty <pre> if no <code> is found.

        # Re-assemble the HTML structure for saving
        body_content = soup.find('body')
        if body_content:
            final_html_output = "<!DOCTYPE html>\n<html>\n<head><title>Final Cleaned Pre Fragments</title></head>\n<body>\n"
            for child in body_content.children:
                final_html_output += str(child)
            final_html_output += "\n</body>\n</html>"
        else:
            # Fallback if no body tag is found
            final_html_output = str(soup)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(final_html_output)

        print(f"Successfully processed '{input_file}' and saved to '{output_file}'.")

    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Define input and output filenames
input_file = 'cleaned-pre-frags.html'
output_file = 'final-cleaned-pre-frags.html'

# Run the final cleaning function
finalize_pre_code_cleaning(input_file, output_file)

from bs4 import BeautifulSoup

def clean_html_fragments(input_file, output_file):
    """
    Reads an HTML file, cleans all elements by removing all attributes,
    unwraps <span> tags within <code>, and saves the cleaned HTML to a new file.
    """
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
        soup = BeautifulSoup(html_content, 'html.parser')

        # Remove all attributes from ALL tags
        for tag in soup.find_all(True):
            tag.attrs = {}

        # Unwrap <span> tags within <code> tags specifically
        for code_tag in soup.find_all('code'):
            for span_tag in code_tag.find_all('span'):
                span_tag.unwrap()

        # Re-assemble the HTML structure for saving
        # The original output included `<body>` and `</html>` tags, so we'll re-use that structure.

        # Find the body to extract its content
        body_content = soup.find('body')
        if body_content:
            cleaned_html_output = "<!DOCTYPE html>\n<html>\n<head><title>Cleaned Pre Fragments</title></head>\n<body>\n"
            # Iterate through the children of the body
            for child in body_content.children:
                # Ensure we get the string representation of each child (tag or NavigableString)
                cleaned_html_output += str(child)
            cleaned_html_output += "\n</body>\n</html>"
        else:
            # Fallback if no body tag is found, though unlikely for valid HTML
            cleaned_html_output = str(soup.prettify())

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(cleaned_html_output)

        print(f"Successfully cleaned '{input_file}' and saved to '{output_file}'.")

    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Define input and output filenames
input_file = 'pre-frags.html'
output_file = 'cleaned-pre-frags.html'

# Run the cleaning function
clean_html_fragments(input_file, output_file)